baseURL = "https://bikodbg.com/"
languageCode = "en-us"
title = "Biko's House of Horrors"

disableKinds = ["taxonomy", "taxonomyTerm"]

# Theme
theme = "simple-hugo-theme"

# Pagination
paginate = 10
paginatePath = "page"

# Copyright
copyright = "© 2021 — Michael Bikovitsky — CC BY-SA 4.0."

# Highlighting
[markup.highlight]
guessSyntax = true
lineNos = true
style = "vs"

# Menu
[menu]
  # Header
  [[menu.main]]
    url = "/blog/"
    name = "blog"
    weight = 1
  [[menu.main]]
    url = "/writing/"
    name = "writing"
    weight = 2
  [[menu.main]]
    url = "/about/"
    name = "about"
    weight = 3

  # Footer
  [[menu.footer]]
    url = "https://github.com/mbikovitsky"
    name = "GitHub"
    weight = 1
  [[menu.footer]]
    url = "https://twitter.com/bikodbg"
    name = "Twitter"
    weight = 2

# Links format
[permalinks]
  blog = "/blog/:year/:month/:filename/"
  writing = "/writing/:year/:month/:filename/"

[markup.goldmark.renderer]
unsafe = true
